---
title: "Netzwerkanalyse #30u30"
author: "hb062"
date: '2022-04-20'
output: html_document
---

```{r wichtigste packages abrufen}

#wir laden nun vorab die wichtigsten packages
library(igraph)
library(igraphdata)
library(knitr) 
library(rmarkdown) 
```

```{r Gesamtnetzwerk einlesen}

# Wir lesen das Netzwerk im Folgenden ein

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/hb062/BA_30u30/main/edges_complete%20-%20edgelist.csv", header=T, as.is=T, sep = ",", fileEncoding="UTF-8")
head(el) # zeigt die ersten Zeilen der Edgelist an

nodes <- read.csv("https://raw.githubusercontent.com/hb062/BA_30u30/main/nodelist_complete%20-%20nodelist.csv", header=T, as.is=T, sep = ",", fileEncoding="UTF-8")

head(nodes) # zeigt die ersten Zeilen der Nodelist an

# Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
gesamtnetzwerk <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)

gesamtnetzwerk

gesamtnetzwerk <- simplify(gesamtnetzwerk, remove.multiple = TRUE) # es werden keine doppelten oder mehrfachen Beziehungen angezeigt

# Visualisierung des Netzwerks
plot(gesamtnetzwerk,
     layout=layout_with_kk,
     edge.curved=curve_multiple(gesamtnetzwerk), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=.1,
     main="Gesamtnetzwerk der #30u30
     (der Jahrgänge 2017 bis 2021)",
     sub="Berufliche und akademische Stationen")

delete.vertices(gesamtnetzwerk, V(gesamtnetzwerk)[degree(gesamtnetzwerk)==0])

delete.vertices(gesamtnetzwerk, V(gesamtnetzwerk)[degree(gesamtnetzwerk)==1])

# Visualisierung des Netzwerks
plot(gesamtnetzwerk,
     vertex.size=degree(gesamtnetzwerk)*1.5,
     layout=layout_with_kk,
     edge.curved=curve_multiple(gesamtnetzwerk), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=.1,
     main="Gesamtnetzwerk der #30u30
     (der Jahrgänge 2017 bis 2021)",
     cex.main=3,
     sub="Berufliche und akademische Stationen")

degree_norm <- degree(gesamtnetzwerk, mode = "all", normalized = T) # retreive normalized degree measure

# Visualisierung des Netzwerks
plot(gesamtnetzwerk,
     vertex.size=degree(gesamtnetzwerk)*1.5,
     layout=layout_with_kk,
     edge.curved=curve_multiple(gesamtnetzwerk), # verhindert, dass sich Kanten überlagern
     vertex.size=.1,
     vertex.label=NA,
     main="Gesamtnetzwerk der #30u30
     (der Jahrgänge 2017 bis 2021)",
     cex.main=3,
     sub="Berufliche und akademische Stationen")

# Zur Prüfung: Abfrage der Attribute
list.vertex.attributes(gesamtnetzwerk)
list.edge.attributes(gesamtnetzwerk)
```
 
```{r Clusteranalyse}

# Um die Überschneidungen der Jahrgänge besser zu greifen, folgt eine Clusteranalyse:
gesamtnetzwerk
gc <- cluster_walktrap(gesamtnetzwerk)
modularity(gc)
membership(gc)
par(mfrow=c(1,1), mar=c(0,0,1,2))

#Visualisierung der Cluster
plot(gc, 
     gesamtnetzwerk, 
     main="Clusteranalyse der #30u30",
     sub="JG 2017 - 2021",
     edge.curved=curve_multiple(gesamtnetzwerk),
     vertex.frame.color="white",
     edge.arrow.size=.2, 
     edge.color="grey",
     edge.curved=.2,
     vertex.size=5,
     vertex.label.degree=0, 
     vertex.label.cex=.15,
     vertex.label.family="Helvetica",
     vertex.label.font=2,
     vertex.label.color="black")

#einmal ohne Vertex-Labels
plot(gc, 
     gesamtnetzwerk, 
     main="Clusteranalyse der #30u30",
     sub="JG 2017 - 2021",
     edge.curved=curve_multiple(gesamtnetzwerk),
     vertex.frame.color="white",
     edge.arrow.size=.2, 
     edge.color="grey",
     edge.curved=.2,
     vertex.size=5,
     vertex.label=NA)

edge_density(gesamtnetzwerk) #berechnet die Dichte des Gesamtnetzwerkes, wobei der Wert an dieser Stelle begrenzte Aussagekraft besitzt

```
```{r Unternetzwerk Studium}
gesamtnetzwerk

# Im nächsten Schritt steht das Netzwerk der #30u30 mit Blick auf deren Hochschulen und Universitäten im Fokus, um mögliche Cluster zu entdecken.

#Hierzu sollen nur die Knoten selektiert werden, bei denen es sich um Hochschulen handelt, sowie die Mitglieder der #30u30. 
universities <- delete_vertices(gesamtnetzwerk, V(gesamtnetzwerk)[category != "5"]) # Selektieren der Knoten, bei denen es sich um Hochschulen handelt

universities <- add_vertices(gesamtnetzwerk, V(gesamtnetzwerk)[mentor = "1"])
# Da im vorherigen Schritt alle Knoten außer den Hochschulen gelöscht wurden, werden hier die #30u30 wieder hinzugefügt, über das Vertex-Attribut mentor, der Wert 1 bezieht sich dabei auf die #30u30 - so werden nur diese, nicht aber die Mentor*innen wieder hinzugefügt.

# Da einige Personen auch als Hilfskraft an Hochschulen gearbeitet haben, sollen nur die Edges selektiert werden, die eine Studiumsverbindung (relationship = 2/3/4) beschreiben. Das Edge-Attribut "relationship" beschreibt mit Werten von 1-21 die Art der Verbindung, in diesem Fall relevant sind: relationship = 2 (Bachelor), 3 (Master), 4 (Auslandssemester), 5 (Promotion) sowie 19 (Magister), 20 (Diplom) und 21 (Staatsexamen); siehe Codebuch.

# Um das Netzwerk nach Edge-Attributen aufzutrennen, werden über den Befehl "subgraph.edges" entsprechende Unternetzwerke erstellt. In diesem Fall soll das neue Netzwerk "studium" generiert werden, in dem alle Studiumsverbindungen dargestellt werden. Da die Arten des Studiums über verschiedene Werte definiert werden, folgen hierfür mehrere Schritte, da nicht nur ein Kantentyp selektiert werden kann

study <- subgraph.edges(universities, E(universities)[relationship == 2]) # selektiert nur die Kanten mit Wert 2
study <- add.edges(universities, E(universities)[relationship == 3]) # fügt die Kanten  wieder hinzu, die ein Masterstudium beschreiben
study <- add.edges(universities, E(universities)[relationship == 4]) # fügt wieder die Kanten hinzu, die ein Auslandssemester beschreiben
study <- add.edges(universities, E(universities)[relationship > 18]) # fügt Kanten mit relationship > 18 wieder hinzu, da die Werte 19, 20 und 21 des Attributs relationship Magister-, Diplom- und Staatsexamenstudien beschreiben

# Löschen der isolierten Knoten / Knoten mit degree 1
delete.vertices(study, V(study)[degree(study) == 0])

delete.vertices(study, V(study)[degree(study) == 1])

plot(study)

# Visualisierung des Netzwerks
plot(study,
     vertex.size=degree(study)*1.5, #stellt Knoten entsprechend ihres Degree-Werts größer dar
     layout=layout_with_kk,
     edge.curved=curve_multiple(study), # verhindert, dass sich Kanten überlagern
     vertex.label.cex=.3, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=.1,
     main="Studiumsnetzwerk der #30u30",
     sub="Akademische Stationen 
    (Hochschulen und Universitäten der JG 2017 - 2021)")

```
 
 